linters-settings:
  exhaustruct:
    exclude:
      - '.+/client\.New$'
      - '.+/client\.Options$'
      - '.+/cobra\.Command$'
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/clastix/kamaji-kubectl-plugin)
  goheader:
    template: |-
      Copyright 2024 Clastix Labs
      SPDX-License-Identifier: Apache-2.0

linters:
  disable:
    - cyclop
    - depguard
    - err113
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - lll
    - wsl
    # deprecated linters
    - exportloopref
  enable-all: true

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
